##configuration for FLAMES barcode matching 
edit_distance: 1
umi_length: 12 

##reference files 
genes_gtf: "/raid/users/krisi/sc-ont/data/hg38_pathogens/genes/genes.gtf"
genome_fa: "/raid/users/krisi/sc-ont/data/hg38_pathogens/fasta/genome.fa"

##sqanti classification
filteringMethod: "rules"